In [44]:
import numpy as np

In [45]:
mylist = [2, 8, 9]
type(mylist)

list

In [46]:
np.array(mylist)

array([2, 8, 9])

In [47]:
myarr = np.array(mylist)

In [48]:
type(myarr)

numpy.ndarray

In [49]:
my_matrix = [[256,2,69], [23,45,7], [34,56,33]]

In [50]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.array(my_matrix)

array([[256,   2,  69],
       [ 23,  45,   7],
       [ 34,  56,  33]])

In [52]:
my_matrix = [[256, 2, 69], [23, 45, 7], [34, 56, 33]]
np.array(my_matrix)

array([[256,   2,  69],
       [ 23,  45,   7],
       [ 34,  56,  33]])

In [53]:
arr = np.array(my_matrix)

In [54]:
arr

array([[256,   2,  69],
       [ 23,  45,   7],
       [ 34,  56,  33]])

In [55]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.arange(1, 250, 20)

array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181, 201, 221, 241])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
mya = np.zeros((5, 5))
mya

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
mya = np.ones((5, 5))
mya

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

linspace — это функция в NumPy, которая создаёт равномерно распределённые точки в заданном диапазоне. Название расшифровывается как “linear space” — линейное пространство

In [60]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [63]:
np.random.rand(1)

array([0.61838601])

In [64]:
np.random.rand(2, 2)

array([[0.38246199, 0.98323089],
       [0.46676289, 0.85994041]])

In [65]:
np.random.randn(2, 2)

array([[-0.52512285,  1.91277127],
       [-2.02671962,  1.11942361]])

In [66]:
np.random.randint(2, 22, 10)

array([ 3, 21, 16,  8, 13,  9, 16,  4, 15, 18], dtype=int32)

In [67]:
np.random.randint(2, 22,(5, 5))

array([[ 5, 19,  9,  5,  3],
       [ 7, 11,  5, 19, 13],
       [ 3, 11,  5, 15, 17],
       [16,  9, 15,  9, 17],
       [14, 19, 16, 14, 10]], dtype=int32)

In [68]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [69]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
arr = arr.reshape(5, 2)
arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [71]:
randarr = np.random.randint(0, 1000, 20)
randarr

array([466, 214, 330, 458,  87, 372,  99, 871, 663, 130, 661, 308, 769,
       343, 491, 413, 805, 385, 191, 955], dtype=int32)

In [72]:
randarr.max()

np.int32(955)

In [73]:
randarr.min()

np.int32(87)

In [74]:
randarr.argmin()

np.int64(4)

In [75]:
randarr.argmax()

np.int64(19)

In [76]:
randarr.dtype

dtype('int32')