In [1]:
import numpy as np

In [2]:
arr = np.arange(2, 20)

In [3]:
arr

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [4]:
print(arr[6])

8


In [5]:
arr[0:5]

array([2, 3, 4, 5, 6])

In [6]:
arr[:10:2]

array([ 2,  4,  6,  8, 10])

In [7]:
arr[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2])

In [8]:
arr[:3]=20
arr

array([20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [9]:
slice_arr = arr[:5]
slice_arr

array([20, 20, 20,  5,  6])

In [10]:
slice_arr[:] = 25
slice_arr

array([25, 25, 25, 25, 25])

In [11]:
arr

array([25, 25, 25, 25, 25,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
arr_2d = np.random.randint(2, 22, (6, 6))
arr_2d

array([[ 9,  3,  6, 10, 11,  2],
       [14, 13,  5,  4, 11, 15],
       [19, 21, 11,  6, 12, 15],
       [ 3,  9, 16, 13,  4, 11],
       [10,  7,  7, 18,  6,  5],
       [15, 13, 13, 15, 11,  6]], dtype=int32)

In [13]:
arr_2d[2, 3]

np.int32(6)

In [14]:
arr_2d[:2, 1:]

array([[ 3,  6, 10, 11,  2],
       [13,  5,  4, 11, 15]], dtype=int32)

In [15]:
arr = np.arange(2, 10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
bool_arr = arr > 4
bool_arr

array([False, False, False,  True,  True,  True,  True,  True])

In [17]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [18]:
arr[arr > 4]

array([5, 6, 7, 8, 9])