In [1]:
import numpy as np

In [21]:
arr = np.arange(5, 15)

In [22]:
arr

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
# arr + 10

In [24]:
# arr - 3

In [25]:
arr + arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [26]:
arr * arr

array([ 25,  36,  49,  64,  81, 100, 121, 144, 169, 196])

In [27]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
2 / arr

array([0.4       , 0.33333333, 0.28571429, 0.25      , 0.22222222,
       0.2       , 0.18181818, 0.16666667, 0.15384615, 0.14285714])

In [29]:
np.sqrt(arr)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [30]:
np.sin(arr)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736])

In [35]:
np.log(arr)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733])

In [36]:
arr.sum()

np.int64(95)

In [37]:
arr.mean()

np.float64(9.5)

In [38]:
arr.max()

np.int64(14)

In [ ]:
arr.var()