In [21]:
import torch

## Тензор
1. Скаляр - одно число - 0 мерный массив
2. Вектор - список чисел - 1 мерный массив
3. Матрица - 2 мерный массив
4. Изображение (RGB) - 3 мерный массив
5. Пачка изображений - 4 мерный массив

In [22]:
scalar = torch.tensor(65)
print(f"Scalar {scalar}, Shape: {scalar.shape}")

vector = torch.tensor([1, 2, 3])
print(f"Vector {vector}, Shape: {vector.shape}")

matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix {matrix}, Shape: {matrix.shape}")

tensor3D = torch.randn((5, 5, 5))
print(f"Tensor3D {tensor3D}, Shape: {tensor3D.shape}")

Scalar 65, Shape: torch.Size([])
Vector tensor([1, 2, 3]), Shape: torch.Size([3])
Matrix tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), Shape: torch.Size([3, 3])
Tensor3D tensor([[[ 3.8496e-01,  2.1249e-01,  7.1601e-01,  5.4832e-01,  6.8292e-01],
         [-1.0182e+00, -1.4110e+00, -1.3729e-01,  1.9934e+00,  4.7916e-01],
         [-4.0169e-01, -7.5775e-01, -4.7358e-01,  4.4885e-02, -7.3122e-01],
         [ 1.9820e+00, -3.3122e-01, -6.9596e-01,  4.1495e-01, -1.7507e+00],
         [ 3.0753e-01, -1.9440e-01, -8.2714e-01,  3.4569e-01,  1.1331e+00]],

        [[ 8.8514e-01,  1.3514e+00,  4.0569e-02, -4.3546e-02, -7.2164e-01],
         [-2.0786e-01, -3.8725e-01, -5.5741e-01, -1.7870e+00,  3.7299e-01],
         [ 1.6689e-01,  1.4799e+00,  1.8931e-01, -1.7771e-01,  8.6726e-01],
         [-1.0826e+00, -2.7342e-01,  9.7453e-01,  4.4431e-01,  7.4575e-01],
         [ 1.4173e+00,  4.7256e-01,  2.3630e+00,  2.2391e-01,  1.0458e+00]],

        [[ 2.1069e+00, -1.3169e-04,  3.0169e-01, -3.3

In [23]:
# tensor generate
print(torch.zeros((5, 5)))
print(torch.ones((5, 5)))
print(torch.randn((5, 5)))
print(torch.arange(0, 20, 2))


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[-1.3172, -0.6969, -0.9404, -1.4682, -0.4449],
        [ 1.6304, -1.2958, -0.2102, -1.3345,  0.8120],
        [-1.8709,  1.9592, -0.4712,  0.1244,  0.7699],
        [ 0.3584, -1.8433,  0.5633, -1.0408, -1.6968],
        [-0.2505,  1.2152,  0.6673, -0.7247,  0.6513]])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [24]:
# math operations
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])
print(a + b) # сложение
print(a * b) # покомпонентное умножение
print(torch.dot(a, b)) # Скалярное умножение
print(a@b)

tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])
tensor(70)
tensor(70)


In [25]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(A, B))
print(A@B)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [28]:
if torch.cuda.is_available():
    device = "cuda"
    print(torch.version.cuda)
    print(torch.cuda.get_device_name(0))
else:
    device = "cpu"
print(device)

cpu
