In [7]:
import torch

## Тензор
1. Скаляр - одно число - 0 мерный массив
2. Вектор - список чисел - 1 мерный массив
3. Матрица - 2 мерный массив
4. Изображение (RGB) - 3 мерный массив
5. Пачка изображений - 4 мерный массив

In [8]:
scalar = torch.tensor(65)
print(f"Scalar {scalar}, Shape: {scalar.shape}")

vector = torch.tensor([1, 2, 3])
print(f"Vector {vector}, Shape: {vector.shape}")

matrix = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Matrix {matrix}, Shape: {matrix.shape}")

tensor3D = torch.randn((5, 5, 5))
print(f"Tensor3D {tensor3D}, Shape: {tensor3D.shape}")

Scalar 65, Shape: torch.Size([])
Vector tensor([1, 2, 3]), Shape: torch.Size([3])
Matrix tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), Shape: torch.Size([3, 3])
Tensor3D tensor([[[-9.0712e-01, -1.5388e+00,  8.6015e-01, -1.1518e+00,  1.2007e+00],
         [-5.8982e-01,  7.5748e-01,  1.5508e+00,  4.4446e-01, -2.0861e-01],
         [-3.5146e-01,  8.8457e-01,  1.0723e+00, -6.9370e-01, -5.8813e-01],
         [-1.2789e+00, -1.6931e+00,  2.5144e-01, -7.2091e-02,  6.3212e-02],
         [ 6.3960e-01, -3.3066e-01,  3.1440e-01, -2.9299e-01,  7.0658e-01]],

        [[ 8.0851e-02,  2.1881e+00, -1.3720e+00,  2.0601e-01,  1.8505e+00],
         [-1.0261e+00, -6.1272e-01,  2.0273e+00, -2.9978e-01,  1.8627e+00],
         [ 2.0328e-01, -6.1733e-02, -7.0927e-01,  1.5153e+00, -6.4281e-01],
         [-1.2747e+00, -8.5577e-01, -1.1010e+00, -9.8937e-01,  2.6324e-01],
         [-1.9069e+00, -2.0234e+00,  4.4268e-01,  6.2804e-02,  1.0474e+00]],

        [[ 4.0438e-01, -6.7999e-01, -2.2959e-04, -1.3

In [9]:
# tensor generate
print(torch.zeros((5, 5)))
print(torch.ones((5, 5)))
print(torch.randn((5, 5)))
print(torch.arange(0, 20, 2))


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[-0.1513,  0.9846,  1.1405, -0.0778,  1.4784],
        [ 1.5220,  0.0880, -1.3089,  0.6238,  0.6009],
        [ 0.6783, -1.1753, -0.8207, -2.1800,  2.0899],
        [ 1.6421,  0.2800,  0.6898, -1.0765,  0.7982],
        [ 0.7001, -2.1789,  0.1904, -1.5299,  0.5986]])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [10]:
# math operations
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])
print(a + b) # сложение
print(a * b) # покомпонентное умножение
print(torch.dot(a, b)) # Скалярное умножение
print(a@b)

tensor([ 6,  8, 10, 12])
tensor([ 5, 12, 21, 32])
tensor(70)
tensor(70)


In [11]:
A = torch.tensor([[1, 2], [3, 4]])
B = torch.tensor([[5, 6], [7, 8]])
print(torch.matmul(A, B))
print(A@B)

tensor([[19, 22],
        [43, 50]])
tensor([[19, 22],
        [43, 50]])


In [12]:
if torch.cuda.is_available():
    device = "cuda"
    print(torch.version.cuda)
    print(torch.cuda.get_device_name(0))
else:
    device = "cpu"
print(device)

cpu
